import '../globals.css';
import localFont from 'next/font/local';
import Header from '../Header';
import GitHubLoginButton from '../GitHubLoginButton';
export const metadata = {
  title: '코깃코깃',
  description: 'Generated by create next app',
};

export default function Login() {
  return (
    <div className="flex flex-col justify-center items-center h-screen">
      <img src="/images/cogit.png" alt="Cogit" className="mb-4" />
      <GitHubLoginButton />
    </div>
  );
}
